### PR TITLE
Implement spinner to indicate loading of query results.

### PR DESCRIPTION
**Pull request by Yojairo**

### CODE REVIEW

**Comment by PaulLockett** [comment]
Add a picture to the pull request.

**Comment by Yojairo** [comment]
> Add a picture to the pull request.

Screenshot 2020-07-20 at 11 00 15 AM

Can't necessarily put a screenshot of the loading page due to it only showing up for less than a second on the page, so here's a picture of it solo from the documentation.

**Comment by Yojairo** [comment]
Accidentally closed.

**Comment by PaulLockett** [comment]
since you have the cards implemented could you add a pic of them?

**Comment by Yojairo** [comment]
Screenshot 2020-07-20 at 12 39 33 PM
Left with placeholder text.

**Comment by PaulLockett** [comment]
> Screenshot 2020-07-20 at 12 39 33 PM
> Left with placeholder text.

We should merge after you decide what data to put here and have a picture of it in this pull request.

**Pull request merged**
